import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const carSpecs = [
  { brand: 'Fiat', model: 'Uno', engine: '1.0 Fire Flex', recommendedOil: '5W-30 API SN', oilCapacity: 2.7, tirePressureFront: 28, tirePressureRear: 28, sparkPlugModel: 'NGK BKR6E', brakeFluidType: 'DOT 4', coolantType: 'Paraflu Rosa', powerAndTorque: '75 cv / 9,9 kgfm', tireSize: '175/70 R14', fuelType: 'Flex', fuelTankCapacity: '48 litros', averageConsumption: '11,6 km/l (C) / 13,4 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H4', trunkCapacity: '280 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Fiat', model: 'Argo', engine: '1.0 Firefly Flex', recommendedOil: '0W-20 API SN', oilCapacity: 2.7, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK LKR7B-9', brakeFluidType: 'DOT 4', coolantType: 'Paraflu Rosa', powerAndTorque: '75 cv / 10,7 kgfm', tireSize: '175/65 R14', fuelType: 'Flex', fuelTankCapacity: '45 litros', averageConsumption: '13,6 km/l (C) / 14,5 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H7', trunkCapacity: '300 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Fiat', model: 'Mobi', engine: '1.0 Fire Flex', recommendedOil: '5W-30 API SN', oilCapacity: 2.7, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK BKR6E', brakeFluidType: 'DOT 4', coolantType: 'Paraflu Rosa', powerAndTorque: '75 cv / 10,7 kgfm', tireSize: '175/65 R14', fuelType: 'Flex', fuelTankCapacity: '44 litros', averageConsumption: '14 km/l (C) / 15,1 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H4', trunkCapacity: '200 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Fiat', model: 'Toro', engine: '2.0 Multijet Diesel', recommendedOil: '5W-30 ACEA C2', oilCapacity: 4.2, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 4', coolantType: 'Paraflu Rosa', powerAndTorque: '176 cv / 27,5 kgfm', tireSize: '225/65 R17', fuelType: 'Flex', fuelTankCapacity: '55 litros', averageConsumption: '9,8 km/l (C) / 11,2 km/l (E)', suspensionType: 'Indep., McPherson / Indep., multibraço', headlightBulb: 'H7 ou LED', trunkCapacity: 'N/D', otherRelevantData: 'Dianteira' },
  { brand: 'Fiat', model: 'Strada', engine: '1.4 Fire Flex', recommendedOil: '5W-30 API SN', oilCapacity: 2.7, tirePressureFront: 29, tirePressureRear: 32, sparkPlugModel: 'NGK BKR6E', brakeFluidType: 'DOT 4', coolantType: 'Paraflu Rosa', powerAndTorque: '107 cv / 13,6 kgfm', tireSize: '175/70 R14', fuelType: 'Flex', fuelTankCapacity: '55 litros', averageConsumption: '13 km/l (C) / 14,7 km/l (E)', suspensionType: 'Indep., McPherson / Eixo rígido', headlightBulb: 'H4', trunkCapacity: 'N/D', otherRelevantData: 'Dianteira' },
  { brand: 'Fiat', model: 'Fastback', engine: '1.3 Turbo', recommendedOil: 'N/D', oilCapacity: 0.0, tirePressureFront: 0, tirePressureRear: 0, sparkPlugModel: 'N/D', brakeFluidType: 'N/D', coolantType: 'N/D', powerAndTorque: '130 cv / 20,4 kgfm', tireSize: 'N/D', fuelType: 'Flex', fuelTankCapacity: '45 litros', averageConsumption: '12,1 km/l (C) / 14,3 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'N/D', trunkCapacity: '516 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Ford', model: 'Ka', engine: '1.0 12V TiVCT Flex', recommendedOil: '5W-20 API SN', oilCapacity: 4.1, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK LTR7A-10', brakeFluidType: 'DOT 4', coolantType: 'Motorcraft Laranja', powerAndTorque: '85 cv / 10,7 kgfm', tireSize: '175/65 R14', fuelType: 'Flex', fuelTankCapacity: '51 litros', averageConsumption: '13 km/l (C) / 15,1 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H4', trunkCapacity: '257 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Ford', model: 'Fiesta', engine: '1.6 16V Sigma Flex', recommendedOil: '5W-30 API SN', oilCapacity: 4.1, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK LTR7A-10', brakeFluidType: 'DOT 4', coolantType: 'Motorcraft Laranja', powerAndTorque: 'N/D / N/D', tireSize: '195/55 R15', fuelType: 'Flex', fuelTankCapacity: '51 litros', averageConsumption: '11,6 km/l (C) / 14,2 km/l (E)', suspensionType: 'Independente, McPherson / Eixo de torção', headlightBulb: 'H7', trunkCapacity: '281 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Ford', model: 'Ecosport', engine: '1.5 12V Dragon Flex', recommendedOil: '5W-20 API SN', oilCapacity: 4.1, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK ILTR6G8G', brakeFluidType: 'DOT 4', coolantType: 'Motorcraft Laranja', powerAndTorque: '137 cv / 16,2 kgfm', tireSize: '205/60 R16', fuelType: 'Flex', fuelTankCapacity: '52 litros', averageConsumption: '11,8 km/l (C) / 13,1 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H4', trunkCapacity: '356 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Ford', model: 'Ranger', engine: '3.2 Duratorq Diesel', recommendedOil: '5W-30 ACEA A5/B5', oilCapacity: 9.8, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 4', coolantType: 'Motorcraft Laranja', powerAndTorque: 'N/D / N/D', tireSize: '265/60 R18', fuelType: 'Diesel', fuelTankCapacity: '80 litros', averageConsumption: 'N/D km/l (C) / N/D km/l (E)', suspensionType: 'Indep., braços sobrepostos / Eixo rígido', headlightBulb: 'H11 ou LED', trunkCapacity: 'N/D', otherRelevantData: 'Traseira' },
  { brand: 'Chevrolet', model: 'Onix', engine: '1.0 12V Turbo Flex', recommendedOil: '0W-20 API SN Dexos 1', oilCapacity: 3.5, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK DILZKR7B11', brakeFluidType: 'DOT 4', coolantType: 'Dex-Cool Laranja', powerAndTorque: '82 cv / 10,6 kgfm', tireSize: '185/65 R15', fuelType: 'Flex', fuelTankCapacity: '44 litros', averageConsumption: '13,5 km/l (C) / 16,3 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H4', trunkCapacity: '303 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Chevrolet', model: 'Tracker', engine: '1.2 12V Turbo Flex', recommendedOil: '0W-20 API SN Dexos 1', oilCapacity: 3.5, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK DILZKR7B11', brakeFluidType: 'DOT 4', coolantType: 'Dex-Cool Laranja', powerAndTorque: '115 cv / 18,9 kgfm', tireSize: '215/55 R17', fuelType: 'Flex', fuelTankCapacity: '44 litros', averageConsumption: '11,5 km/l (C) / 13,8 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H4 ou LED', trunkCapacity: '393 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Chevrolet', model: 'Cruze', engine: '1.4 16V Turbo Flex', recommendedOil: '0W-20 API SN Dexos 1', oilCapacity: 4.0, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK ILTR6M9G', brakeFluidType: 'DOT 4', coolantType: 'Dex-Cool Laranja', powerAndTorque: '153 cv / 24,5 kgfm', tireSize: '215/50 R17', fuelType: 'Flex', fuelTankCapacity: '52 litros', averageConsumption: '10,5 km/l (C) / 13,9 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H7 ou LED', trunkCapacity: '440 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Chevrolet', model: 'S10', engine: '2.8 CTDI Diesel', recommendedOil: '5W-30 Dexos 2', oilCapacity: 5.7, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 4', coolantType: 'Dex-Cool Laranja', powerAndTorque: 'N/D / N/D', tireSize: '265/60 R18', fuelType: 'Diesel', fuelTankCapacity: '76 litros', averageConsumption: 'N/D km/l (C) / N/D km/l (E)', suspensionType: 'Indep., braços sobrepostos / Eixo rígido', headlightBulb: 'H7', trunkCapacity: 'N/D', otherRelevantData: 'Integral temporária' },
  { brand: 'Chevrolet', model: 'Montana', engine: '1.2 Turbo', recommendedOil: 'N/D', oilCapacity: 0.0, tirePressureFront: 0, tirePressureRear: 0, sparkPlugModel: 'N/D', brakeFluidType: 'N/D', coolantType: 'N/D', powerAndTorque: '141 cv / 22,9 kgfm', tireSize: 'N/D', fuelType: 'Flex', fuelTankCapacity: '44 litros', averageConsumption: '12,3 km/l (C) / 13,7 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'N/D', trunkCapacity: 'N/D', otherRelevantData: 'Dianteira' },
  { brand: 'Volkswagen', model: 'Gol', engine: '1.0 12V MPI Flex', recommendedOil: '5W-40 VW 502.00', oilCapacity: 3.3, tirePressureFront: 29, tirePressureRear: 29, sparkPlugModel: 'NGK BKUR5ET-10', brakeFluidType: 'DOT 4', coolantType: 'G12 Rosa', powerAndTorque: '84 cv / 10,4 kgfm', tireSize: '175/70 R14', fuelType: 'Flex', fuelTankCapacity: '55 litros', averageConsumption: '13,7 km/l (C) / 15,2 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H4', trunkCapacity: '263 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Volkswagen', model: 'Polo', engine: '1.0 12V TSI Flex', recommendedOil: '5W-40 VW 502.00', oilCapacity: 4.0, tirePressureFront: 33, tirePressureRear: 33, sparkPlugModel: 'NGK PZKER7A8EGS', brakeFluidType: 'DOT 4', coolantType: 'G13 Rosa', powerAndTorque: '116 cv / 16,8 kgfm', tireSize: '195/55 R16', fuelType: 'Flex', fuelTankCapacity: '49 litros', averageConsumption: '13,9 km/l (C) / 16,3 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H7 ou LED', trunkCapacity: '300 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Volkswagen', model: 'T-Cross', engine: '1.4 16V TSI Flex', recommendedOil: '5W-40 VW 502.00', oilCapacity: 4.0, tirePressureFront: 33, tirePressureRear: 33, sparkPlugModel: 'NGK PZKER7A8EGS', brakeFluidType: 'DOT 4', coolantType: 'G13 Rosa', powerAndTorque: '128 cv / 20,4 kgfm', tireSize: '205/55 R17', fuelType: 'Flex', fuelTankCapacity: '49 litros', averageConsumption: '12,1 km/l (C) / 14,5 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H7 ou LED', trunkCapacity: '373 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Volkswagen', model: 'Amarok', engine: '2.0 TDI Diesel', recommendedOil: '5W-30 VW 507.00', oilCapacity: 7.0, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 4', coolantType: 'G13 Rosa', powerAndTorque: 'N/D / N/D', tireSize: '255/60 R18', fuelType: 'Diesel', fuelTankCapacity: '80 litros', averageConsumption: 'N/D km/l (C) / N/D km/l (E)', suspensionType: 'Indep., braços sobrepostos / Eixo rígido', headlightBulb: 'H7 ou LED', trunkCapacity: 'N/D', otherRelevantData: 'Integral permanente' },
  { brand: 'Volkswagen', model: 'Nivus', engine: '1.0 TSI', recommendedOil: 'N/D', oilCapacity: 0.0, tirePressureFront: 0, tirePressureRear: 0, sparkPlugModel: 'N/D', brakeFluidType: 'N/D', coolantType: 'N/D', powerAndTorque: '128 cv / 20,4 kgfm', tireSize: 'N/D', fuelType: 'Flex', fuelTankCapacity: '49 litros', averageConsumption: '12,4 km/l (C) / 14,8 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'N/D', trunkCapacity: '415 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Volkswagen', model: 'Taos', engine: '1.4 TSI', recommendedOil: 'N/D', oilCapacity: 0.0, tirePressureFront: 0, tirePressureRear: 0, sparkPlugModel: 'N/D', brakeFluidType: 'N/D', coolantType: 'N/D', powerAndTorque: '150 cv / 25,5 kgfm', tireSize: 'N/D', fuelType: 'Flex', fuelTankCapacity: '48 litros', averageConsumption: '11,1 km/l (C) / 13,3 km/l (E)', suspensionType: 'Indep., McPherson / Indep., multibraço', headlightBulb: 'N/D', trunkCapacity: '498 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Hyundai', model: 'HB20', engine: '1.0 12V Kappa Flex', recommendedOil: '5W-30 API SN', oilCapacity: 2.9, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK LKR7B-9', brakeFluidType: 'DOT 4', coolantType: 'Hyundai Verde', powerAndTorque: '80 cv / 10,2 kgfm', tireSize: '175/70 R14', fuelType: 'Flex', fuelTankCapacity: '50 litros', averageConsumption: '13,3 km/l (C) / 15,4 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H4', trunkCapacity: '300 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Hyundai', model: 'Creta', engine: '1.6 16V Gamma Flex', recommendedOil: '5W-30 API SN', oilCapacity: 3.6, tirePressureFront: 33, tirePressureRear: 33, sparkPlugModel: 'NGK SILZKR7B11', brakeFluidType: 'DOT 4', coolantType: 'Hyundai Verde', powerAndTorque: '120 cv / 17,5 kgfm', tireSize: '205/65 R16', fuelType: 'Flex', fuelTankCapacity: '50 litros', averageConsumption: '12 km/l (C) / 12,7 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H4 ou Projector', trunkCapacity: '422 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Hyundai', model: 'Tucson', engine: '1.6 16V T-GDI', recommendedOil: '5W-30 API SN', oilCapacity: 4.5, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK SILZKR7B11', brakeFluidType: 'DOT 4', coolantType: 'Hyundai Verde', powerAndTorque: 'N/D / N/D', tireSize: '225/55 R18', fuelType: 'Gasolina', fuelTankCapacity: '62 litros', averageConsumption: '10,6 km/l (C) / 12,2 km/l (E)', suspensionType: 'Indep., McPherson / Indep., multibraço', headlightBulb: 'LED', trunkCapacity: '513 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Honda', model: 'Civic', engine: '2.0 16V i-VTEC Flex', recommendedOil: '0W-20 API SN', oilCapacity: 3.7, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK SILZKR7C11S', brakeFluidType: 'DOT 4', coolantType: 'Honda Azul', powerAndTorque: 'N/D / N/D', tireSize: '215/50 R17', fuelType: 'Gasolina', fuelTankCapacity: '40 litros', averageConsumption: '18,4 km/l (C) / 15,9 km/l (E)', suspensionType: 'Indep., McPherson / Indep., multibraço', headlightBulb: 'H11 ou LED', trunkCapacity: '495 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Honda', model: 'HR-V', engine: '1.8 16V i-VTEC Flex', recommendedOil: '0W-20 API SN', oilCapacity: 3.7, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK SILZKR7C11S', brakeFluidType: 'DOT 4', coolantType: 'Honda Azul', powerAndTorque: '177 cv / 24,5 kgfm', tireSize: '215/55 R17', fuelType: 'Flex', fuelTankCapacity: '50 litros', averageConsumption: '11,5 km/l (C) / 12,9 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H4 ou LED', trunkCapacity: '354 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Honda', model: 'Fit', engine: '1.5 16V i-VTEC Flex', recommendedOil: '0W-20 API SN', oilCapacity: 3.6, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK DILZKR7A11G', brakeFluidType: 'DOT 4', coolantType: 'Honda Azul', powerAndTorque: '116 cv / 15,3 kgfm', tireSize: '185/55 R16', fuelType: 'Flex', fuelTankCapacity: '45 litros', averageConsumption: '11,6 km/l (C) / 13,6 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H4', trunkCapacity: '363 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Mitsubishi', model: 'L200 Triton', engine: '2.4 16V DI-D Diesel', recommendedOil: '5W-30 ACEA A5/B5', oilCapacity: 8.4, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 4', coolantType: 'Mitsubishi Long Life', powerAndTorque: '190 cv / 43,9 kgfm', tireSize: '265/60 R18', fuelType: 'Diesel', fuelTankCapacity: '75 L', averageConsumption: '9.5 km/l (C) / 11.5 km/l (E)', suspensionType: 'Duplo A / Eixo Rígido', headlightBulb: 'LED', trunkCapacity: '1046 L (Caçamba)', otherRelevantData: 'N/D' },
  { brand: 'Mitsubishi', model: 'ASX', engine: '2.0 16V MIVEC Flex', recommendedOil: '5W-30 API SN', oilCapacity: 4.3, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK DILFR5A11', brakeFluidType: 'DOT 4', coolantType: 'Mitsubishi Long Life', powerAndTorque: 'N/D / N/D', tireSize: '225/55 R18', fuelType: 'Flex', fuelTankCapacity: '60 litros', averageConsumption: '9,8 km/l (C) / 12,6 km/l (E)', suspensionType: 'Independente, McPherson / Independente, multibraço', headlightBulb: 'H11 ou LED', trunkCapacity: '415 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Subaru', model: 'Forester', engine: '2.0 16V Boxer', recommendedOil: '0W-20 API SN', oilCapacity: 4.8, tirePressureFront: 32, tirePressureRear: 30, sparkPlugModel: 'NGK SILZKAR7B11', brakeFluidType: 'DOT 4', coolantType: 'Subaru Super Coolant', powerAndTorque: 'N/D / N/D', tireSize: '225/60 R17', fuelType: 'Gasolina', fuelTankCapacity: '48 litros', averageConsumption: '12 km/l (C) / 12,2 km/l (E)', suspensionType: 'Indep., McPherson / Indep., braços sobrepostos', headlightBulb: 'LED', trunkCapacity: '520 litros', otherRelevantData: 'Integral permanente' },
  { brand: 'Subaru', model: 'XV', engine: '2.0 16V Boxer', recommendedOil: '0W-20 API SN', oilCapacity: 4.8, tirePressureFront: 33, tirePressureRear: 32, sparkPlugModel: 'NGK SILZKAR7B11', brakeFluidType: 'DOT 4', coolantType: 'Subaru Super Coolant', powerAndTorque: 'N/D / N/D', tireSize: '225/55 R18', fuelType: 'Gasolina', fuelTankCapacity: '48 litros', averageConsumption: '12,1 km/l (C) / 12,3 km/l (E)', suspensionType: 'Indep., McPherson / Indep., braços sobrepostos', headlightBulb: 'LED', trunkCapacity: '380 litros', otherRelevantData: 'Integral permanente' },
  { brand: 'Chery', model: 'Tiggo 5X', engine: '1.5 16V Turbo Flex', recommendedOil: '5W-40 API SN', oilCapacity: 4.5, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'BOSCH YR7SES', brakeFluidType: 'DOT 4', coolantType: 'Chery Orgânico', powerAndTorque: '150 cv / 21,4 kgfm', tireSize: '215/55 R18', fuelType: 'Flex', fuelTankCapacity: '51 litros', averageConsumption: '10 km/l (C) / 12,1 km/l (E)', suspensionType: 'Indep., McPherson / Indep., multibraço', headlightBulb: 'LED', trunkCapacity: '340 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Chery', model: 'Tiggo 8', engine: '1.6 16V TGDI', recommendedOil: '5W-30 API SN', oilCapacity: 4.5, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK ILKAR7B11', brakeFluidType: 'DOT 4', coolantType: 'Chery Orgânico', powerAndTorque: 'N/D / N/D', tireSize: '235/55 R18', fuelType: 'Eletricidade/gasolina', fuelTankCapacity: '60 litros', averageConsumption: 'N/D km/l (C) / N/D km/l (E)', suspensionType: 'Indep., McPherson / Indep., multibraço', headlightBulb: 'LED', trunkCapacity: 'N/D', otherRelevantData: 'Dianteira' },
  { brand: 'Toyota', model: 'Corolla', engine: '2.0 16V Dual VVT-iE Flex', recommendedOil: '0W-20 API SN', oilCapacity: 4.2, tirePressureFront: 33, tirePressureRear: 33, sparkPlugModel: 'NGK DILKAR7B11', brakeFluidType: 'DOT 3', coolantType: 'Toyota Super Long Life (Rosa)', powerAndTorque: '175 cv / 21,3 kgfm', tireSize: '225/45 R17', fuelType: 'Flex', fuelTankCapacity: '50 litros', averageConsumption: '11,9 km/l (C) / 14,5 km/l (E)', suspensionType: 'Indep., McPherson / Indep., multibraço', headlightBulb: 'HIR2 ou LED', trunkCapacity: '470 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Toyota', model: 'Hilux', engine: '2.8 16V D-4D Diesel', recommendedOil: '5W-30 ACEA C2/C3', oilCapacity: 7.5, tirePressureFront: 29, tirePressureRear: 29, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 3', coolantType: 'Toyota Super Long Life (Rosa)', powerAndTorque: 'N/D / N/D', tireSize: '265/60 R18', fuelType: 'Diesel', fuelTankCapacity: '80 litros', averageConsumption: 'N/D km/l (C) / N/D km/l (E)', suspensionType: 'Indep., braços sobrepostos / Eixo rígido', headlightBulb: 'LED', trunkCapacity: '1195 litros', otherRelevantData: 'Integral temporária' },
  { brand: 'Toyota', model: 'Yaris', engine: '1.5 16V Flex', recommendedOil: '5W-30 API SN', oilCapacity: 3.3, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK ILKAR7B11', brakeFluidType: 'DOT 3', coolantType: 'Toyota Super Long Life (Rosa)', powerAndTorque: '110 cv / 14,9 kgfm', tireSize: '185/60 R15', fuelType: 'Flex', fuelTankCapacity: '45 litros', averageConsumption: '12,2 km/l (C) / 13,8 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H4 ou Projector', trunkCapacity: '310 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Jeep', model: 'Compass', engine: '1.3 16V Turbo Flex', recommendedOil: '0W-20 API SN', oilCapacity: 4.5, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK SILZKR7B11', brakeFluidType: 'DOT 4', coolantType: 'Mopar Orgânico Vermelho', powerAndTorque: 'N/D / N/D', tireSize: '225/55 R18', fuelType: 'Gasolina', fuelTankCapacity: '55 litros', averageConsumption: '8,5 km/l (C) / 10,8 km/l (E)', suspensionType: 'Indep., McPherson / Indep., McPherson', headlightBulb: 'LED', trunkCapacity: '410 litros', otherRelevantData: 'Integral sob demanda' },
  { brand: 'Jeep', model: 'Renegade', engine: '1.8 16V E.torQ Flex', recommendedOil: '5W-30 API SN', oilCapacity: 4.3, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK BKR7E-10', brakeFluidType: 'DOT 4', coolantType: 'Mopar Orgânico Vermelho', powerAndTorque: '176 cv / 27,5 kgfm', tireSize: '215/60 R17', fuelType: 'Flex', fuelTankCapacity: '55 litros', averageConsumption: '11,1 km/l (C) / 12,4 km/l (E)', suspensionType: 'Indep., McPherson / Indep., McPherson', headlightBulb: 'H4 ou LED', trunkCapacity: '320 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Jeep', model: 'Commander', engine: '2.0 16V Multijet Diesel', recommendedOil: '5W-30 ACEA C2', oilCapacity: 4.2, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 4', coolantType: 'Mopar Orgânico Vermelho', powerAndTorque: 'N/D / N/D', tireSize: '235/50 R19', fuelType: 'Gasolina', fuelTankCapacity: '61 litros', averageConsumption: '8 km/l (C) / 10,3 km/l (E)', suspensionType: 'Indep., McPherson / Indep., McPherson', headlightBulb: 'LED', trunkCapacity: 'N/D', otherRelevantData: 'Integral sob demanda' },
  { brand: 'Nissan', model: 'Kicks', engine: '1.6 16V Flex', recommendedOil: '5W-30 API SN', oilCapacity: 4.3, tirePressureFront: 33, tirePressureRear: 33, sparkPlugModel: 'NGK PLKAR6A-11', brakeFluidType: 'DOT 4', coolantType: 'Nissan Azul', powerAndTorque: '125 cv / 22,4 kgfm', tireSize: '205/55 R17', fuelType: 'Flex', fuelTankCapacity: '45 litros', averageConsumption: '12 km/l (C) / 13 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H11 ou LED', trunkCapacity: '450 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Nissan', model: 'Frontier', engine: '2.3 16V Bi-Turbo Diesel', recommendedOil: '5W-30 ACEA C4', oilCapacity: 6.3, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 4', coolantType: 'Nissan L255N Azul', powerAndTorque: 'N/D / N/D', tireSize: '255/60 R18', fuelType: 'Diesel', fuelTankCapacity: '73 litros', averageConsumption: 'N/D km/l (C) / N/D km/l (E)', suspensionType: 'Indep., braços sobrepostos / Eixo rígido', headlightBulb: 'LED', trunkCapacity: 'N/D', otherRelevantData: 'Integral temporária' },
  { brand: 'Nissan', model: 'Versa', engine: '1.6 16V Flex', recommendedOil: '5W-30 API SN', oilCapacity: 4.3, tirePressureFront: 33, tirePressureRear: 33, sparkPlugModel: 'NGK PLKAR6A-11', brakeFluidType: 'DOT 4', coolantType: 'Nissan Azul', powerAndTorque: '113 cv / 15,3 kgfm', tireSize: '205/50 R17', fuelType: 'Flex', fuelTankCapacity: '41 litros', averageConsumption: '11,5 km/l (C) / 15 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'LED', trunkCapacity: '482 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Peugeot', model: '208', engine: '1.6 16V EC5 Flex', recommendedOil: '5W-30 API SN', oilCapacity: 3.2, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'BOSCH FR8SE0', brakeFluidType: 'DOT 4', coolantType: 'Total Glacelf', powerAndTorque: '130 cv / 20,4 kgfm', tireSize: '195/55 R16', fuelType: 'Flex', fuelTankCapacity: '47 litros', averageConsumption: '12,6 km/l (C) / 14,3 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H7 ou LED', trunkCapacity: '265 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Peugeot', model: '3008', engine: '1.6 16V THP', recommendedOil: '0W-30 ACEA C2', oilCapacity: 4.2, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK PLZKBR7A-G', brakeFluidType: 'DOT 4', coolantType: 'Total Glacelf', powerAndTorque: 'N/D / N/D', tireSize: '225/55 R18', fuelType: 'Gasolina', fuelTankCapacity: '53 litros', averageConsumption: '9,9 km/l (C) / 11,9 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'LED', trunkCapacity: '520 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Citroen', model: 'C4 Cactus', engine: '1.6 16V THP Flex', recommendedOil: '0W-30 ACEA C2', oilCapacity: 4.2, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK PLZKBR7A-G', brakeFluidType: 'DOT 4', coolantType: 'Total Glacelf', powerAndTorque: '120 cv / 15,7 kgfm', tireSize: '205/55 R17', fuelType: 'Flex', fuelTankCapacity: '55 litros', averageConsumption: '11,2 km/l (C) / 12,7 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H7', trunkCapacity: '320 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Citroen', model: 'C3', engine: '1.2 12V PureTech', recommendedOil: '0W-30 ACEA C2', oilCapacity: 3.5, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK LZKR6B-10E', brakeFluidType: 'DOT 4', coolantType: 'Total Glacelf', powerAndTorque: '75 cv / 10,7 kgfm', tireSize: '195/60 R15', fuelType: 'Flex', fuelTankCapacity: '47 litros', averageConsumption: '13,2 km/l (C) / 14,5 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H4', trunkCapacity: '315 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Renault', model: 'Kwid', engine: '1.0 12V SCe Flex', recommendedOil: '10W-40 API SN', oilCapacity: 2.9, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK LZKAR7B', brakeFluidType: 'DOT 4', coolantType: 'Renault Glaceol RX Type D', powerAndTorque: '71 cv / 10 kgfm', tireSize: '165/70 R14', fuelType: 'Flex', fuelTankCapacity: '38 litros', averageConsumption: '14,6 km/l (C) / 15,5 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H4', trunkCapacity: '290 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Renault', model: 'Sandero', engine: '1.0 12V SCe Flex', recommendedOil: '10W-40 API SN', oilCapacity: 2.9, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK LZKAR7B', brakeFluidType: 'DOT 4', coolantType: 'Renault Glaceol RX Type D', powerAndTorque: 'a2 cv / 10,5 kgfm', tireSize: '185/65 R15', fuelType: 'Flex', fuelTankCapacity: '50 litros', averageConsumption: '13 km/l (C) / 13,7 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H4 ou H7', trunkCapacity: '320 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Renault', model: 'Duster', engine: '1.6 16V SCe Flex', recommendedOil: '10W-40 API SN', oilCapacity: 4.3, tirePressureFront: 30, tirePressureRear: 30, sparkPlugModel: 'NGK LZKAR7B', brakeFluidType: 'DOT 4', coolantType: 'Renault Glaceol RX Type D', powerAndTorque: '163 cv / 27,5 kgfm', tireSize: '215/65 R16', fuelType: 'Flex', fuelTankCapacity: '46 litros', averageConsumption: '10,9 km/l (C) / 12,3 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'H7', trunkCapacity: '475 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Renault', model: 'Virtus', engine: '1.0 200 TSI Flex', recommendedOil: '5W-40 VW 502.00', oilCapacity: 4.0, tirePressureFront: 33, tirePressureRear: 33, sparkPlugModel: 'NGK PZKER7A8EGS', brakeFluidType: 'DOT 4', coolantType: 'G13 Rosa', powerAndTorque: '128 cv / 20,4 kgfm', tireSize: '205/55 R17', fuelType: 'Flex', fuelTankCapacity: '52 L', averageConsumption: '11.0 km/l (C) / 14.0 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H7 ou LED', trunkCapacity: '521 L', otherRelevantData: 'N/D' },
  { brand: 'Renault', model: 'HB20S', engine: '1.0 12V TGDI Flex', recommendedOil: '5W-30 API SN', oilCapacity: 2.9, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK SILZKBR8D8G', brakeFluidType: 'DOT 4', coolantType: 'Hyundai Verde', powerAndTorque: '120 cv / 17,5 kgfm', tireSize: '185/60 R15', fuelType: 'Flex', fuelTankCapacity: '50 L', averageConsumption: '11.0 km/l (C) / 14.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4 ou Projector', trunkCapacity: '475 L', otherRelevantData: 'N/D' },
  { brand: 'Renault', model: 'Pulse', engine: '1.0 Turbo 200 Flex', recommendedOil: '0W-20 API SN', oilCapacity: 3.5, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK ILKR8P8', brakeFluidType: 'DOT 4', coolantType: 'Paraflu Rosa', powerAndTorque: '130 cv / 20,4 kgfm', tireSize: '195/60 R16', fuelType: 'Flex', fuelTankCapacity: '47 L', averageConsumption: '10.5 km/l (C) / 13.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'LED', trunkCapacity: '370 L', otherRelevantData: 'N/D' },
  { brand: 'Renault', model: 'Compass', engine: '2.0 Multijet II Diesel', recommendedOil: '5W-30 ACEA C2', oilCapacity: 4.2, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 4', coolantType: 'Mopar Orgânico Vermelho', powerAndTorque: '170 cv / 35,7 kgfm', tireSize: '225/55 R18', fuelType: 'Diesel', fuelTankCapacity: '60 L', averageConsumption: '10.5 km/l (C) / 13.5 km/l (E)', suspensionType: 'MacPherson / MacPherson', headlightBulb: 'LED', trunkCapacity: '410 L', otherRelevantData: 'Tração 4x4' },
  { brand: 'Renault', model: 'Corolla Cross', engine: '1.8 16V VVT-i Hybrid', recommendedOil: '0W-20 API SN', oilCapacity: 4.2, tirePressureFront: 33, tirePressureRear: 33, sparkPlugModel: 'NGK FC20HR-Q8', brakeFluidType: 'DOT 3', coolantType: 'Toyota Super Long Life (Rosa)', powerAndTorque: '122 cv (Combinado)', tireSize: '225/50 R18', fuelType: 'Flex', fuelTankCapacity: '36 L', averageConsumption: '17.0 km/l (C) / 14.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'LED', trunkCapacity: '440 L', otherRelevantData: 'Sistema Híbrido' },
  { brand: 'Renault', model: 'Spin', engine: '1.8 8V SPE/4 Eco Flex', recommendedOil: '0W-20 API SN Dexos 1', oilCapacity: 3.5, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK BPR6EY', brakeFluidType: 'DOT 4', coolantType: 'Dex-Cool Laranja', powerAndTorque: '111 cv / 17,7 kgfm', tireSize: '195/65 R15', fuelType: 'Flex', fuelTankCapacity: '53 L', averageConsumption: '10.0 km/l (C) / 12.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4', trunkCapacity: '710 L (5 lug) / 162 L (7 lug)', otherRelevantData: 'N/D' },
  { brand: 'Renault', model: 'City', engine: '1.5 16V DI DOHC i-VTEC', recommendedOil: '0W-20 API SN', oilCapacity: 3.6, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK DILZKAR7C11S', brakeFluidType: 'DOT 4', coolantType: 'Honda Azul', powerAndTorque: '126 cv / 15,5 kgfm', tireSize: '185/55 R16', fuelType: 'Flex', fuelTankCapacity: '39 L', averageConsumption: '11.5 km/l (C) / 15.0 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'LED', trunkCapacity: '519 L', otherRelevantData: 'N/D' },
  { brand: 'Renault', model: 'Duster', engine: '1.3 TCe Flex', recommendedOil: '5W-30 API SN', oilCapacity: 4.5, tirePressureFront: 30, tirePressureRear: 30, sparkPlugModel: 'NGK ILKAR7B11', brakeFluidType: 'DOT 4', coolantType: 'Renault Glaceol RX Type D', powerAndTorque: '163 cv / 27,5 kgfm', tireSize: '215/60 R17', fuelType: 'Flex', fuelTankCapacity: '46 litros', averageConsumption: '10,9 km/l (C) / 12,3 km/l (E)', suspensionType: 'Indep., McPherson / Eixo de torção', headlightBulb: 'LED', trunkCapacity: '475 litros', otherRelevantData: 'Dianteira' },
  { brand: 'Renault', model: 'Sentra', engine: '2.0 16V CVT Gasolina', recommendedOil: '0W-20 API SN', oilCapacity: 4.0, tirePressureFront: 33, tirePressureRear: 33, sparkPlugModel: 'NGK DILKAR6A-11', brakeFluidType: 'DOT 4', coolantType: 'Nissan Azul', powerAndTorque: '151 cv / 20,0 kgfm', tireSize: '215/50 R17', fuelType: 'Gasolina', fuelTankCapacity: '47 L', averageConsumption: '11.0 km/l (C) / 14.0 km/l (E)', suspensionType: 'MacPherson / Multi-link', headlightBulb: 'LED', trunkCapacity: '466 L', otherRelevantData: 'N/D' },
  { brand: 'Renault', model: '2008', engine: '1.6 16V THP Flex', recommendedOil: '0W-30 ACEA C2', oilCapacity: 4.2, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK PLZKBR7A-G', brakeFluidType: 'DOT 4', coolantType: 'Total Glacelf', powerAndTorque: '173 cv / 24,5 kgfm', tireSize: '205/60 R16', fuelType: 'Flex', fuelTankCapacity: '55 L', averageConsumption: '9.5 km/l (C) / 12.0 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H7', trunkCapacity: '355 L', otherRelevantData: 'N/D' },
];

async function main() {
  console.log(`Iniciando seed do banco de dados com ${carSpecs.length} modelos atualizados...`);
  await prisma.carSpecsReference.deleteMany();
  await prisma.carSpecsReference.createMany({
    data: carSpecs,
  });
  console.log(`Seed concluído com sucesso. ${carSpecs.length} registros inseridos.`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
