import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const carSpecs = [
  // FIAT
  { brand: 'Fiat', model: 'Uno', engine: '1.0 Fire Flex', recommendedOil: '5W-30 API SN', oilCapacity: 2.7, tirePressureFront: 28, tirePressureRear: 28, sparkPlugModel: 'NGK BKR6E', brakeFluidType: 'DOT 4', coolantType: 'Paraflu Rosa', powerAndTorque: '75 cv / 9,9 kgfm', tireSize: '175/70 R14', fuelType: 'Flex', fuelTankCapacity: '48 L', averageConsumption: '9.0 km/l (C) / 11.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4', trunkCapacity: '280 L', otherRelevantData: 'N/D' },
  { brand: 'Fiat', model: 'Argo', engine: '1.0 Firefly Flex', recommendedOil: '0W-20 API SN', oilCapacity: 2.7, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK LKR7B-9', brakeFluidType: 'DOT 4', coolantType: 'Paraflu Rosa', powerAndTorque: '77 cv / 10,9 kgfm', tireSize: '175/65 R14', fuelType: 'Flex', fuelTankCapacity: '48 L', averageConsumption: '10.5 km/l (C) / 13.0 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H7', trunkCapacity: '300 L', otherRelevantData: 'N/D' },
  { brand: 'Fiat', model: 'Mobi', engine: '1.0 Fire Flex', recommendedOil: '5W-30 API SN', oilCapacity: 2.7, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK BKR6E', brakeFluidType: 'DOT 4', coolantType: 'Paraflu Rosa', powerAndTorque: '75 cv / 9,9 kgfm', tireSize: '175/65 R14', fuelType: 'Flex', fuelTankCapacity: '47 L', averageConsumption: '9.5 km/l (C) / 12.0 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4', trunkCapacity: '235 L', otherRelevantData: 'N/D' },
  { brand: 'Fiat', model: 'Toro', engine: '2.0 Multijet Diesel', recommendedOil: '5W-30 ACEA C2', oilCapacity: 4.2, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 4', coolantType: 'Paraflu Rosa', powerAndTorque: '170 cv / 35,7 kgfm', tireSize: '225/65 R17', fuelType: 'Diesel', fuelTankCapacity: '60 L', averageConsumption: '10.0 km/l (C) / 12.5 km/l (E)', suspensionType: 'MacPherson / Multi-link', headlightBulb: 'H7 ou LED', trunkCapacity: '820 L', otherRelevantData: 'N/D' },
  { brand: 'Fiat', model: 'Strada', engine: '1.4 Fire Flex', recommendedOil: '5W-30 API SN', oilCapacity: 2.7, tirePressureFront: 29, tirePressureRear: 32, sparkPlugModel: 'NGK BKR6E', brakeFluidType: 'DOT 4', coolantType: 'Paraflu Rosa', powerAndTorque: '86 cv / 12,4 kgfm', tireSize: '175/70 R14', fuelType: 'Flex', fuelTankCapacity: '55 L', averageConsumption: '8.5 km/l (C) / 10.5 km/l (E)', suspensionType: 'MacPherson / Eixo Rígido', headlightBulb: 'H4', trunkCapacity: '1354 L (Caçamba)', otherRelevantData: 'N/D' },

  // FORD
  { brand: 'Ford', model: 'Ka', engine: '1.0 12V TiVCT Flex', recommendedOil: '5W-20 API SN', oilCapacity: 4.1, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK LTR7A-10', brakeFluidType: 'DOT 4', coolantType: 'Motorcraft Laranja', powerAndTorque: '85 cv / 10,7 kgfm', tireSize: '175/65 R14', fuelType: 'Flex', fuelTankCapacity: '51 L', averageConsumption: '10.0 km/l (C) / 13.0 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4', trunkCapacity: '257 L', otherRelevantData: 'N/D' },
  { brand: 'Ford', model: 'Fiesta', engine: '1.6 16V Sigma Flex', recommendedOil: '5W-30 API SN', oilCapacity: 4.1, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK LTR7A-10', brakeFluidType: 'DOT 4', coolantType: 'Motorcraft Laranja', powerAndTorque: '128 cv / 16,0 kgfm', tireSize: '195/55 R15', fuelType: 'Flex', fuelTankCapacity: '51 L', averageConsumption: '9.0 km/l (C) / 11.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H7', trunkCapacity: '281 L', otherRelevantData: 'N/D' },
  { brand: 'Ford', model: 'Ecosport', engine: '1.5 12V Dragon Flex', recommendedOil: '5W-20 API SN', oilCapacity: 4.1, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK ILTR6G8G', brakeFluidType: 'DOT 4', coolantType: 'Motorcraft Laranja', powerAndTorque: '137 cv / 16,2 kgfm', tireSize: '205/60 R16', fuelType: 'Flex', fuelTankCapacity: '52 L', averageConsumption: '9.0 km/l (C) / 11.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4', trunkCapacity: '356 L', otherRelevantData: 'N/D' },
  { brand: 'Ford', model: 'Ranger', engine: '3.2 Duratorq Diesel', recommendedOil: '5W-30 ACEA A5/B5', oilCapacity: 9.8, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 4', coolantType: 'Motorcraft Laranja', powerAndTorque: '200 cv / 47,9 kgfm', tireSize: '265/60 R18', fuelType: 'Diesel', fuelTankCapacity: '80 L', averageConsumption: '8.5 km/l (C) / 10.5 km/l (E)', suspensionType: 'Duplo A / Eixo Rígido', headlightBulb: 'H11 ou LED', trunkCapacity: '1180 L (Caçamba)', otherRelevantData: 'N/D' },

  // CHEVROLET
  { brand: 'Chevrolet', model: 'Onix', engine: '1.0 12V Turbo Flex', recommendedOil: '0W-20 API SN Dexos 1', oilCapacity: 3.5, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK DILZKR7B11', brakeFluidType: 'DOT 4', coolantType: 'Dex-Cool Laranja', powerAndTorque: '116 cv / 16,8 kgfm', tireSize: '185/65 R15', fuelType: 'Flex', fuelTankCapacity: '44 L', averageConsumption: '11.5 km/l (C) / 14.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4', trunkCapacity: '275 L', otherRelevantData: 'N/D' },
  { brand: 'Chevrolet', model: 'Tracker', engine: '1.2 12V Turbo Flex', recommendedOil: '0W-20 API SN Dexos 1', oilCapacity: 3.5, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK DILZKR7B11', brakeFluidType: 'DOT 4', coolantType: 'Dex-Cool Laranja', powerAndTorque: '133 cv / 21,4 kgfm', tireSize: '215/55 R17', fuelType: 'Flex', fuelTankCapacity: '44 L', averageConsumption: '10.5 km/l (C) / 13.0 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4 ou LED', trunkCapacity: '393 L', otherRelevantData: 'N/D' },
  { brand: 'Chevrolet', model: 'Cruze', engine: '1.4 16V Turbo Flex', recommendedOil: '0W-20 API SN Dexos 1', oilCapacity: 4.0, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK ILTR6M9G', brakeFluidType: 'DOT 4', coolantType: 'Dex-Cool Laranja', powerAndTorque: '153 cv / 24,5 kgfm', tireSize: '215/50 R17', fuelType: 'Flex', fuelTankCapacity: '52 L', averageConsumption: '10.0 km/l (C) / 13.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H7 ou LED', trunkCapacity: '440 L', otherRelevantData: 'N/D' },
  { brand: 'Chevrolet', model: 'S10', engine: '2.8 CTDI Diesel', recommendedOil: '5W-30 Dexos 2', oilCapacity: 5.7, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 4', coolantType: 'Dex-Cool Laranja', powerAndTorque: '200 cv / 51,0 kgfm', tireSize: '265/60 R18', fuelType: 'Diesel', fuelTankCapacity: '76 L', averageConsumption: '8.5 km/l (C) / 10.5 km/l (E)', suspensionType: 'Duplo A / Eixo Rígido', headlightBulb: 'H7', trunkCapacity: '1061 L (Caçamba)', otherRelevantData: 'N/D' },

  // VW
  { brand: 'Volkswagen', model: 'Gol', engine: '1.0 12V MPI Flex', recommendedOil: '5W-40 VW 502.00', oilCapacity: 3.3, tirePressureFront: 29, tirePressureRear: 29, sparkPlugModel: 'NGK BKUR5ET-10', brakeFluidType: 'DOT 4', coolantType: 'G12 Rosa', powerAndTorque: '84 cv / 10,4 kgfm', tireSize: '175/70 R14', fuelType: 'Flex', fuelTankCapacity: '55 L', averageConsumption: '10.0 km/l (C) / 13.0 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4', trunkCapacity: '285 L', otherRelevantData: 'N/D' },
  { brand: 'Volkswagen', model: 'Polo', engine: '1.0 12V TSI Flex', recommendedOil: '5W-40 VW 502.00', oilCapacity: 4.0, tirePressureFront: 33, tirePressureRear: 33, sparkPlugModel: 'NGK PZKER7A8EGS', brakeFluidType: 'DOT 4', coolantType: 'G13 Rosa', powerAndTorque: '128 cv / 20,4 kgfm', tireSize: '195/55 R16', fuelType: 'Flex', fuelTankCapacity: '52 L', averageConsumption: '11.0 km/l (C) / 14.0 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H7 ou LED', trunkCapacity: '300 L', otherRelevantData: 'N/D' },
  { brand: 'Volkswagen', model: 'T-Cross', engine: '1.4 16V TSI Flex', recommendedOil: '5W-40 VW 502.00', oilCapacity: 4.0, tirePressureFront: 33, tirePressureRear: 33, sparkPlugModel: 'NGK PZKER7A8EGS', brakeFluidType: 'DOT 4', coolantType: 'G13 Rosa', powerAndTorque: '150 cv / 25,5 kgfm', tireSize: '205/55 R17', fuelType: 'Flex', fuelTankCapacity: '52 L', averageConsumption: '10.0 km/l (C) / 13.0 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H7 ou LED', trunkCapacity: '373 L', otherRelevantData: 'N/D' },
  { brand: 'Volkswagen', model: 'Amarok', engine: '2.0 TDI Diesel', recommendedOil: '5W-30 VW 507.00', oilCapacity: 7.0, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 4', coolantType: 'G13 Rosa', powerAndTorque: '180 cv / 42,8 kgfm', tireSize: '255/60 R18', fuelType: 'Diesel', fuelTankCapacity: '80 L', averageConsumption: '9.0 km/l (C) / 11.5 km/l (E)', suspensionType: 'Duplo A / Eixo Rígido', headlightBulb: 'H7 ou LED', trunkCapacity: '1280 L (Caçamba)', otherRelevantData: 'N/D' },

  // HYUNDAI
  { brand: 'Hyundai', model: 'HB20', engine: '1.0 12V Kappa Flex', recommendedOil: '5W-30 API SN', oilCapacity: 2.9, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK LKR7B-9', brakeFluidType: 'DOT 4', coolantType: 'Hyundai Verde', powerAndTorque: '80 cv / 10,2 kgfm', tireSize: '175/70 R14', fuelType: 'Flex', fuelTankCapacity: '50 L', averageConsumption: '10.5 km/l (C) / 13.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4', trunkCapacity: '300 L', otherRelevantData: 'N/D' },
  { brand: 'Hyundai', model: 'Creta', engine: '1.6 16V Gamma Flex', recommendedOil: '5W-30 API SN', oilCapacity: 3.6, tirePressureFront: 33, tirePressureRear: 33, sparkPlugModel: 'NGK SILZKR7B11', brakeFluidType: 'DOT 4', coolantType: 'Hyundai Verde', powerAndTorque: '130 cv / 16,5 kgfm', tireSize: '205/65 R16', fuelType: 'Flex', fuelTankCapacity: '55 L', averageConsumption: '9.5 km/l (C) / 12.0 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4 ou Projector', trunkCapacity: '431 L', otherRelevantData: 'N/D' },
  { brand: 'Hyundai', model: 'Tucson', engine: '1.6 16V T-GDI', recommendedOil: '5W-30 API SN', oilCapacity: 4.5, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK SILZKR7B11', brakeFluidType: 'DOT 4', coolantType: 'Hyundai Verde', powerAndTorque: '177 cv / 27,0 kgfm', tireSize: '225/55 R18', fuelType: 'Gasolina', fuelTankCapacity: '62 L', averageConsumption: '10.0 km/l (C) / 12.5 km/l (E)', suspensionType: 'MacPherson / Multi-link', headlightBulb: 'LED', trunkCapacity: '513 L', otherRelevantData: 'N/D' },

  // HONDA
  { brand: 'Honda', model: 'Civic', engine: '2.0 16V i-VTEC Flex', recommendedOil: '0W-20 API SN', oilCapacity: 3.7, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK SILZKR7C11S', brakeFluidType: 'DOT 4', coolantType: 'Honda Azul', powerAndTorque: '155 cv / 19,5 kgfm', tireSize: '215/50 R17', fuelType: 'Flex', fuelTankCapacity: '56 L', averageConsumption: '9.5 km/l (C) / 12.5 km/l (E)', suspensionType: 'MacPherson / Multi-link', headlightBulb: 'H11 ou LED', trunkCapacity: '525 L', otherRelevantData: 'N/D' },
  { brand: 'Honda', model: 'HR-V', engine: '1.8 16V i-VTEC Flex', recommendedOil: '0W-20 API SN', oilCapacity: 3.7, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK SILZKR7C11S', brakeFluidType: 'DOT 4', coolantType: 'Honda Azul', powerAndTorque: '140 cv / 17,4 kgfm', tireSize: '215/55 R17', fuelType: 'Flex', fuelTankCapacity: '51 L', averageConsumption: '9.5 km/l (C) / 12.0 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4 ou LED', trunkCapacity: '437 L', otherRelevantData: 'N/D' },
  { brand: 'Honda', model: 'Fit', engine: '1.5 16V i-VTEC Flex', recommendedOil: '0W-20 API SN', oilCapacity: 3.6, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK DILZKR7A11G', brakeFluidType: 'DOT 4', coolantType: 'Honda Azul', powerAndTorque: '116 cv / 15,3 kgfm', tireSize: '185/55 R16', fuelType: 'Flex', fuelTankCapacity: '40 L', averageConsumption: '10.5 km/l (C) / 13.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4', trunkCapacity: '363 L', otherRelevantData: 'N/D' },

  // MITSUBISHI
  { brand: 'Mitsubishi', model: 'L200 Triton', engine: '2.4 16V DI-D Diesel', recommendedOil: '5W-30 ACEA A5/B5', oilCapacity: 8.4, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 4', coolantType: 'Mitsubishi Long Life', powerAndTorque: '190 cv / 43,9 kgfm', tireSize: '265/60 R18', fuelType: 'Diesel', fuelTankCapacity: '75 L', averageConsumption: '9.5 km/l (C) / 11.5 km/l (E)', suspensionType: 'Duplo A / Eixo Rígido', headlightBulb: 'LED', trunkCapacity: '1046 L (Caçamba)', otherRelevantData: 'N/D' },
  { brand: 'Mitsubishi', model: 'ASX', engine: '2.0 16V MIVEC Flex', recommendedOil: '5W-30 API SN', oilCapacity: 4.3, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK DILFR5A11', brakeFluidType: 'DOT 4', coolantType: 'Mitsubishi Long Life', powerAndTorque: '170 cv / 23,0 kgfm', tireSize: '225/55 R18', fuelType: 'Flex', fuelTankCapacity: '60 L', averageConsumption: '8.5 km/l (C) / 10.5 km/l (E)', suspensionType: 'MacPherson / Multi-link', headlightBulb: 'H11 ou LED', trunkCapacity: '415 L', otherRelevantData: 'N/D' },

  // SUBARU
  { brand: 'Subaru', model: 'Forester', engine: '2.0 16V Boxer', recommendedOil: '0W-20 API SN', oilCapacity: 4.8, tirePressureFront: 32, tirePressureRear: 30, sparkPlugModel: 'NGK SILZKAR7B11', brakeFluidType: 'DOT 4', coolantType: 'Subaru Super Coolant', powerAndTorque: '156 cv / 20,0 kgfm', tireSize: '225/60 R17', fuelType: 'Gasolina', fuelTankCapacity: '63 L', averageConsumption: '9.5 km/l (C) / 12.0 km/l (E)', suspensionType: 'MacPherson / Double Wishbone', headlightBulb: 'LED', trunkCapacity: '520 L', otherRelevantData: 'Symmetrical AWD' },
  { brand: 'Subaru', model: 'XV', engine: '2.0 16V Boxer', recommendedOil: '0W-20 API SN', oilCapacity: 4.8, tirePressureFront: 33, tirePressureRear: 32, sparkPlugModel: 'NGK SILZKAR7B11', brakeFluidType: 'DOT 4', coolantType: 'Subaru Super Coolant', powerAndTorque: '156 cv / 20,0 kgfm', tireSize: '225/55 R18', fuelType: 'Gasolina', fuelTankCapacity: '63 L', averageConsumption: '10.0 km/l (C) / 13.0 km/l (E)', suspensionType: 'MacPherson / Double Wishbone', headlightBulb: 'LED', trunkCapacity: '310 L', otherRelevantData: 'Symmetrical AWD' },

  // CHERY
  { brand: 'Chery', model: 'Tiggo 5X', engine: '1.5 16V Turbo Flex', recommendedOil: '5W-40 API SN', oilCapacity: 4.5, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'BOSCH YR7SES', brakeFluidType: 'DOT 4', coolantType: 'Chery Orgânico', powerAndTorque: '150 cv / 21,4 kgfm', tireSize: '215/55 R18', fuelType: 'Flex', fuelTankCapacity: '51 L', averageConsumption: '9.5 km/l (C) / 11.5 km/l (E)', suspensionType: 'MacPherson / Multi-link', headlightBulb: 'LED', trunkCapacity: '340 L', otherRelevantData: 'N/D' },
  { brand: 'Chery', model: 'Tiggo 8', engine: '1.6 16V TGDI', recommendedOil: '5W-30 API SN', oilCapacity: 4.5, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK ILKAR7B11', brakeFluidType: 'DOT 4', coolantType: 'Chery Orgânico', powerAndTorque: '187 cv / 28,0 kgfm', tireSize: '235/55 R18', fuelType: 'Gasolina', fuelTankCapacity: '51 L', averageConsumption: '9.0 km/l (C) / 11.5 km/l (E)', suspensionType: 'MacPherson / Multi-link', headlightBulb: 'LED', trunkCapacity: '193 L (7 lug) / 889 L (5 lug)', otherRelevantData: 'N/D' },

  // TOYOTA
  { brand: 'Toyota', model: 'Corolla', engine: '2.0 16V Dual VVT-iE Flex', recommendedOil: '0W-20 API SN', oilCapacity: 4.2, tirePressureFront: 33, tirePressureRear: 33, sparkPlugModel: 'NGK DILKAR7B11', brakeFluidType: 'DOT 3', coolantType: 'Toyota Super Long Life (Rosa)', powerAndTorque: '177 cv / 21,4 kgfm', tireSize: '225/45 R17', fuelType: 'Flex', fuelTankCapacity: '50 L', averageConsumption: '10.5 km/l (C) / 13.0 km/l (E)', suspensionType: 'MacPherson / Double Wishbone', headlightBulb: 'HIR2 ou LED', trunkCapacity: '470 L', otherRelevantData: 'N/D' },
  { brand: 'Toyota', model: 'Hilux', engine: '2.8 16V D-4D Diesel', recommendedOil: '5W-30 ACEA C2/C3', oilCapacity: 7.5, tirePressureFront: 29, tirePressureRear: 29, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 3', coolantType: 'Toyota Super Long Life (Rosa)', powerAndTorque: '204 cv / 50,9 kgfm', tireSize: '265/60 R18', fuelType: 'Diesel', fuelTankCapacity: '80 L', averageConsumption: '9.0 km/l (C) / 11.5 km/l (E)', suspensionType: 'Duplo A / Eixo Rígido', headlightBulb: 'LED', trunkCapacity: '1000 L (Caçamba)', otherRelevantData: 'N/D' },
  { brand: 'Toyota', model: 'Yaris', engine: '1.5 16V Flex', recommendedOil: '5W-30 API SN', oilCapacity: 3.3, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK ILKAR7B11', brakeFluidType: 'DOT 3', coolantType: 'Toyota Super Long Life (Rosa)', powerAndTorque: '110 cv / 14,9 kgfm', tireSize: '185/60 R15', fuelType: 'Flex', fuelTankCapacity: '45 L', averageConsumption: '11.0 km/l (C) / 13.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4 ou Projector', trunkCapacity: '310 L (Hatch)', otherRelevantData: 'N/D' },

  // JEEP
  { brand: 'Jeep', model: 'Compass', engine: '1.3 16V Turbo Flex', recommendedOil: '0W-20 API SN', oilCapacity: 4.5, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK SILZKR7B11', brakeFluidType: 'DOT 4', coolantType: 'Mopar Orgânico Vermelho', powerAndTorque: '185 cv / 27,5 kgfm', tireSize: '225/55 R18', fuelType: 'Flex', fuelTankCapacity: '60 L', averageConsumption: '9.5 km/l (C) / 12.0 km/l (E)', suspensionType: 'MacPherson / MacPherson', headlightBulb: 'LED', trunkCapacity: '410 L', otherRelevantData: 'N/D' },
  { brand: 'Jeep', model: 'Renegade', engine: '1.8 16V E.torQ Flex', recommendedOil: '5W-30 API SN', oilCapacity: 4.3, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK BKR7E-10', brakeFluidType: 'DOT 4', coolantType: 'Mopar Orgânico Vermelho', powerAndTorque: '139 cv / 19,3 kgfm', tireSize: '215/60 R17', fuelType: 'Flex', fuelTankCapacity: '60 L', averageConsumption: '8.5 km/l (C) / 10.5 km/l (E)', suspensionType: 'MacPherson / MacPherson', headlightBulb: 'H4 ou LED', trunkCapacity: '320 L', otherRelevantData: 'N/D' },
  { brand: 'Jeep', model: 'Commander', engine: '2.0 16V Multijet Diesel', recommendedOil: '5W-30 ACEA C2', oilCapacity: 4.2, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 4', coolantType: 'Mopar Orgânico Vermelho', powerAndTorque: '170 cv / 38,7 kgfm', tireSize: '235/50 R19', fuelType: 'Diesel', fuelTankCapacity: '61 L', averageConsumption: '10.0 km/l (C) / 13.0 km/l (E)', suspensionType: 'MacPherson / MacPherson', headlightBulb: 'LED', trunkCapacity: '233 L (7 lug) / 661 L (5 lug)', otherRelevantData: 'N/D' },

  // NISSAN
  { brand: 'Nissan', model: 'Kicks', engine: '1.6 16V Flex', recommendedOil: '5W-30 API SN', oilCapacity: 4.3, tirePressureFront: 33, tirePressureRear: 33, sparkPlugModel: 'NGK PLKAR6A-11', brakeFluidType: 'DOT 4', coolantType: 'Nissan Azul', powerAndTorque: '114 cv / 15,5 kgfm', tireSize: '205/55 R17', fuelType: 'Flex', fuelTankCapacity: '41 L', averageConsumption: '10.5 km/l (C) / 13.0 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H11 ou LED', trunkCapacity: '432 L', otherRelevantData: 'N/D' },
  { brand: 'Nissan', model: 'Frontier', engine: '2.3 16V Bi-Turbo Diesel', recommendedOil: '5W-30 ACEA C4', oilCapacity: 6.3, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'N/A', brakeFluidType: 'DOT 4', coolantType: 'Nissan L255N Azul', powerAndTorque: '190 cv / 45,9 kgfm', tireSize: '255/60 R18', fuelType: 'Diesel', fuelTankCapacity: '73 L', averageConsumption: '9.0 km/l (C) / 11.5 km/l (E)', suspensionType: 'Duplo A / Multilink Eixo Rígido', headlightBulb: 'LED', trunkCapacity: '1054 L (Caçamba)', otherRelevantData: 'N/D' },
  { brand: 'Nissan', model: 'Versa', engine: '1.6 16V Flex', recommendedOil: '5W-30 API SN', oilCapacity: 4.3, tirePressureFront: 33, tirePressureRear: 33, sparkPlugModel: 'NGK PLKAR6A-11', brakeFluidType: 'DOT 4', coolantType: 'Nissan Azul', powerAndTorque: '114 cv / 15,5 kgfm', tireSize: '205/50 R17', fuelType: 'Flex', fuelTankCapacity: '41 L', averageConsumption: '11.0 km/l (C) / 14.0 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'LED', trunkCapacity: '482 L', otherRelevantData: 'N/D' },

  // PEUGEOT
  { brand: 'Peugeot', model: '208', engine: '1.6 16V EC5 Flex', recommendedOil: '5W-30 API SN', oilCapacity: 3.2, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'BOSCH FR8SE0', brakeFluidType: 'DOT 4', coolantType: 'Total Glacelf', powerAndTorque: '118 cv / 15,5 kgfm', tireSize: '195/55 R16', fuelType: 'Flex', fuelTankCapacity: '47 L', averageConsumption: '9.5 km/l (C) / 12.0 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H7 ou LED', trunkCapacity: '265 L', otherRelevantData: 'N/D' },
  { brand: 'Peugeot', model: '3008', engine: '1.6 16V THP', recommendedOil: '0W-30 ACEA C2', oilCapacity: 4.2, tirePressureFront: 35, tirePressureRear: 35, sparkPlugModel: 'NGK PLZKBR7A-G', brakeFluidType: 'DOT 4', coolantType: 'Total Glacelf', powerAndTorque: '165 cv / 24,5 kgfm', tireSize: '225/55 R18', fuelType: 'Gasolina', fuelTankCapacity: '53 L', averageConsumption: '10.0 km/l (C) / 12.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'LED', trunkCapacity: '520 L', otherRelevantData: 'N/D' },

  // CITROEN
  { brand: 'Citroen', model: 'C4 Cactus', engine: '1.6 16V THP Flex', recommendedOil: '0W-30 ACEA C2', oilCapacity: 4.2, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK PLZKBR7A-G', brakeFluidType: 'DOT 4', coolantType: 'Total Glacelf', powerAndTorque: '173 cv / 24,5 kgfm', tireSize: '205/55 R17', fuelType: 'Flex', fuelTankCapacity: '55 L', averageConsumption: '9.5 km/l (C) / 12.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H7', trunkCapacity: '320 L', otherRelevantData: 'N/D' },
  { brand: 'Citroen', model: 'C3', engine: '1.2 12V PureTech', recommendedOil: '0W-30 ACEA C2', oilCapacity: 3.5, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK LZKR6B-10E', brakeFluidType: 'DOT 4', coolantType: 'Total Glacelf', powerAndTorque: '90 cv / 13,0 kgfm', tireSize: '195/60 R15', fuelType: 'Flex', fuelTankCapacity: '55 L', averageConsumption: '11.0 km/l (C) / 14.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4', trunkCapacity: '300 L', otherRelevantData: 'N/D' },

  // RENAULT
  { brand: 'Renault', model: 'Kwid', engine: '1.0 12V SCe Flex', recommendedOil: '10W-40 API SN', oilCapacity: 2.9, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK LZKAR7B', brakeFluidType: 'DOT 4', coolantType: 'Renault Glaceol RX Type D', powerAndTorque: '71 cv / 10,0 kgfm', tireSize: '165/70 R14', fuelType: 'Flex', fuelTankCapacity: '38 L', averageConsumption: '12.0 km/l (C) / 14.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4', trunkCapacity: '290 L', otherRelevantData: 'N/D' },
  { brand: 'Renault', model: 'Sandero', engine: '1.0 12V SCe Flex', recommendedOil: '10W-40 API SN', oilCapacity: 2.9, tirePressureFront: 32, tirePressureRear: 32, sparkPlugModel: 'NGK LZKAR7B', brakeFluidType: 'DOT 4', coolantType: 'Renault Glaceol RX Type D', powerAndTorque: '82 cv / 10,5 kgfm', tireSize: '185/65 R15', fuelType: 'Flex', fuelTankCapacity: '50 L', averageConsumption: '10.5 km/l (C) / 13.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H4 ou H7', trunkCapacity: '320 L', otherRelevantData: 'N/D' },
  { brand: 'Renault', model: 'Duster', engine: '1.6 16V SCe Flex', recommendedOil: '10W-40 API SN', oilCapacity: 4.3, tirePressureFront: 30, tirePressureRear: 30, sparkPlugModel: 'NGK LZKAR7B', brakeFluidType: 'DOT 4', coolantType: 'Renault Glaceol RX Type D', powerAndTorque: '120 cv / 16,2 kgfm', tireSize: '215/65 R16', fuelType: 'Flex', fuelTankCapacity: '50 L', averageConsumption: '9.0 km/l (C) / 11.5 km/l (E)', suspensionType: 'MacPherson / Eixo de Torção', headlightBulb: 'H7', trunkCapacity: '475 L', otherRelevantData: 'N/D' },
];

async function main() {
  console.log('Iniciando seed do banco de dados com 43 modelos expandidos (15 marcas)...');
  await prisma.carSpecsReference.deleteMany();
  for (const spec of carSpecs) {
    await prisma.carSpecsReference.upsert({
      where: {
        brand_model_engine: { brand: spec.brand, model: spec.model, engine: spec.engine }
      },
      update: {},
      create: spec
    });
  }
  console.log(`Seed concluído com sucesso. ${carSpecs.length} registros inseridos.`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
